### PR TITLE
More comments in UWP project

### PR DESCRIPTION
**Pull request by JayKim94**
# Related issues:

#221

### CODE REVIEW

**Comment by JonasMuehlmann** [comment]
@JayKim94 Apparently the `AzureServiceBase.cs.example` disappeared from unstable, could you add it to this branch?

**Comment by JayKim94** [comment]
> @JayKim94 Apparently the `AzureServiceBase.cs.example` disappeared from unstable, could you add it to this branch?

added 👍

**Comment by JonasMuehlmann** [comment]
@JayKim94 Well, the CI pipeline is still broken...
I can fix it tomorrow.

**Comment by JayKim94** [comment]
oh it succeeded?

**Review by JonasMuehlmann — APPROVED** [review]

**Pull request merged**
